require 'opal/minitest/rake_task'

# Register code in /opal with Opal.
Opal.append_path File.expand_path('../opal', __FILE__)

Opal::Minitest::RakeTask.new

desc "Run tests through regular Minitest"
task('regtest') do
  require 'minitest'
  require 'minitest/autorun'

  %w[opal test].each { |p| $LOAD_PATH << p }

  require_relative 'test/test_helper.rb'
  Dir['test/**/*_test.rb'].each { |f| require_relative f }
end
